language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-sails-nanzi' ]; then cd .. && eval "mv $currentfolder generator-sails-nanzi" && cd generator-sails-nanzi; fi
